# Generated by Django 6.0.6 on 2026-06-30 10:22

import formbuilder.models
import utils.storage
import utils.translation
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the creation of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update of the object', verbose_name='updated at')),
                ('title', utils.translation.TranslateableTextField(blank=True, default=dict, verbose_name='title')),
                ('description', utils.translation.TranslateableTextField(blank=True, default=dict, verbose_name='description')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('is_readonly', models.BooleanField(default=False, verbose_name='is readonly')),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='The total budget for this edition', max_digits=14, verbose_name='total edition budget')),
                ('individual_budget', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='The maximum budget per project', max_digits=14, verbose_name='individual project budget')),
                ('budget_currency', models.CharField(blank=True, max_length=3, verbose_name='budget currency')),
                ('cached_begins_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cached_ends_on', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'edition',
                'verbose_name_plural': 'editions',
            },
        ),
        migrations.CreateModel(
            name='EditionPublicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the creation of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update of the object', verbose_name='updated at')),
                ('uploaded_document', models.FileField(blank=True, null=True, storage=utils.storage.select_public_storage, upload_to='editions_public/%Y/%m/', verbose_name='uploaded document')),
                ('linked_document_url', models.CharField(blank=True, default='', help_text='If the user entered a link instead of a file upload', max_length=2048, verbose_name='linked document URL')),
            ],
            options={
                'verbose_name': 'edition public document',
                'verbose_name_plural': 'edition public documents',
            },
        ),
        migrations.CreateModel(
            name='EditionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the creation of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update of the object', verbose_name='updated at')),
                ('title', utils.translation.TranslateableTextField(blank=True, default=dict, verbose_name='title')),
                ('stage_type', models.CharField(choices=[('FORM', 'Form Completion'), ('JURY', 'Jury Scoring'), ('OTHER', 'Other')], default='FORM', max_length=5, verbose_name='stage type')),
                ('description', utils.translation.TranslateableTextField(blank=True, default=dict, verbose_name='description')),
                ('begins_on', models.DateTimeField(verbose_name='begins on')),
                ('ends_on', models.DateTimeField(verbose_name='ends on')),
            ],
            options={
                'verbose_name': 'edition stage',
                'verbose_name_plural': 'edition stages',
            },
        ),
        migrations.CreateModel(
            name='FinancingDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the creation of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update of the object', verbose_name='updated at')),
                ('title', utils.translation.TranslateableTextField(blank=True, default=dict, verbose_name='title')),
            ],
            options={
                'verbose_name': 'financing domain',
                'verbose_name_plural': 'financing domains',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='JuryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the creation of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update of the object', verbose_name='updated at')),
                ('title', utils.translation.TranslateableTextField(blank=True, default=dict, verbose_name='title')),
                ('fieldset', formbuilder.models.FieldsetField(blank=True, default=dict, verbose_name='fieldset')),
                ('min_score', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='minimum score')),
                ('max_score', models.PositiveSmallIntegerField(blank=True, default=10, verbose_name='maximum score')),
            ],
            options={
                'verbose_name': 'jury form',
                'verbose_name_plural': 'jury forms',
            },
        ),
        migrations.CreateModel(
            name='JuryScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the creation of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update of the object', verbose_name='updated at')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='data')),
                ('total_score', models.PositiveSmallIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'jury scorecard',
                'verbose_name_plural': 'jury scorecards',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the creation of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update of the object', verbose_name='updated at')),
                ('title', utils.translation.TranslateableTextField(blank=True, default=dict, verbose_name='title')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the creation of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update of the object', verbose_name='updated at')),
                ('title', utils.translation.TranslateableTextField(blank=True, default=dict, verbose_name='title')),
                ('message', utils.translation.TranslateableTextField(blank=True, default=dict, verbose_name='message')),
            ],
            options={
                'verbose_name': 'project comment',
                'verbose_name_plural': 'project comments',
            },
        ),
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the creation of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update of the object', verbose_name='updated at')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='data')),
            ],
            options={
                'verbose_name': 'project data',
                'verbose_name_plural': 'project data',
            },
        ),
        migrations.CreateModel(
            name='ProjectDataDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the creation of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update of the object', verbose_name='updated at')),
                ('uploaded_document', models.FileField(blank=True, null=True, upload_to='projects/%Y/%m/', verbose_name='uploaded document')),
                ('linked_document_url', models.CharField(blank=True, default='', help_text='If the user entered a link instead of a file upload', max_length=2048, verbose_name='linked document URL')),
            ],
            options={
                'verbose_name': 'project data document',
                'verbose_name_plural': 'project data documents',
            },
        ),
        migrations.CreateModel(
            name='ProjectForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the creation of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update of the object', verbose_name='updated at')),
                ('title', utils.translation.TranslateableTextField(blank=True, default=dict, verbose_name='title')),
                ('fieldset', formbuilder.models.FieldsetField(blank=True, default=dict, verbose_name='fieldset')),
            ],
            options={
                'verbose_name': 'project form',
                'verbose_name_plural': 'project forms',
            },
        ),
        migrations.CreateModel(
            name='ProjectJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the creation of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update of the object', verbose_name='updated at')),
                ('cached_total_score', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('cached_average_score', models.FloatField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'project jury',
                'verbose_name_plural': 'project juries',
            },
        ),
    ]
