# Generated by Django 6.0.6 on 2026-06-30 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='jury_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='jury users'),
        ),
        migrations.AddField(
            model_name='editionpublicdocument',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editions.edition', verbose_name='edition'),
        ),
        migrations.AddField(
            model_name='editionstage',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editions.edition', verbose_name='edition'),
        ),
        migrations.AddField(
            model_name='financingdomain',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editions.edition', verbose_name='edition'),
        ),
        migrations.AddField(
            model_name='editionstage',
            name='jury_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editions.juryform', verbose_name='jury form'),
        ),
        migrations.AddField(
            model_name='juryscorecard',
            name='edition_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editions.editionstage', verbose_name='edition stage'),
        ),
        migrations.AddField(
            model_name='juryscorecard',
            name='jury_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='jury user'),
        ),
        migrations.AddField(
            model_name='project',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editions.edition', verbose_name='edition'),
        ),
        migrations.AddField(
            model_name='juryscorecard',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editions.project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='parent_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editions.projectcomment', verbose_name='parent comment'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editions.project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='edition_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editions.editionstage', verbose_name='edition stage'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editions.project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='projectdatadocument',
            name='project_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editions.projectdata', verbose_name='project data'),
        ),
        migrations.AddField(
            model_name='editionstage',
            name='project_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editions.projectform', verbose_name='project form'),
        ),
        migrations.AddField(
            model_name='projectjury',
            name='edition_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editions.editionstage', verbose_name='edition stage'),
        ),
        migrations.AddField(
            model_name='projectjury',
            name='jury_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='jury users'),
        ),
        migrations.AddField(
            model_name='projectjury',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editions.project', verbose_name='project'),
        ),
    ]
