# Generated by Django 6.0.6 on 2026-07-22 08:25

import utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editionpublicdocument',
            name='uploaded_document',
            field=models.FileField(blank=True, null=True, storage=utils.storage.select_public_storage, upload_to='editions_public/%Y/%W/', verbose_name='uploaded document'),
        ),
        migrations.AlterField(
            model_name='projectdatadocument',
            name='uploaded_document',
            field=models.FileField(blank=True, null=True, upload_to='projects/%Y/%W/', verbose_name='uploaded document'),
        ),
    ]
