# Generated by Django 6.0.6 on 2026-06-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the creation of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update of the object', verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the creation of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update of the object', verbose_name='updated at')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='organization details')),
            ],
            options={
                'verbose_name': 'organization details',
                'verbose_name_plural': 'organization details',
            },
        ),
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_document', models.FileField(blank=True, null=True, upload_to='orgs/%Y/%m/', verbose_name='uploaded document')),
                ('linked_document_url', models.CharField(blank=True, default='', help_text='If the user entered a link instead of a file upload', max_length=2048, verbose_name='linked document URL')),
            ],
            options={
                'verbose_name': 'organization document',
                'verbose_name_plural': 'organization documents',
            },
        ),
    ]
