# Generated by Django 6.0.6 on 2026-06-30 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
        migrations.CreateModel(
            name='OrganizationDetailsSnapshot',
            fields=[
                ('organizationdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orgs.organizationdetails')),
            ],
            options={
                'verbose_name': 'organization details snapshot',
                'verbose_name_plural': 'organization details snapshots',
            },
            bases=('orgs.organizationdetails',),
        ),
        migrations.AddField(
            model_name='organizationdetails',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization'),
        ),
        migrations.AddField(
            model_name='organizationdocument',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization'),
        ),
        migrations.AddField(
            model_name='organizationdocument',
            name='referencing_snapshots',
            field=models.ManyToManyField(to='orgs.organizationdetailssnapshot', verbose_name='referencing snapshots'),
        ),
    ]
