# Generated by Django 6.0.6 on 2026-07-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationdocument',
            name='uploaded_document',
            field=models.FileField(blank=True, null=True, upload_to='orgs/%Y/%W/', verbose_name='uploaded document'),
        ),
    ]
