# Generated by Django 6.0.6 on 2026-07-22 08:19

import django.core.validators
import django.db.models.deletion
import utils.models
import utils.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, null=True, storage=utils.storage.select_public_storage, upload_to='profiles_public/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png')), utils.models.MaxFileSizeValidator(2097152)], verbose_name='picture')),
                ('accepted_newsletter', models.DateTimeField(blank=True, null=True, verbose_name='Accepted to receive newsletters')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'ordering': ['user__email'],
            },
        ),
    ]
