# Generated by Django 6.0.6 on 2026-07-22 08:25

import django.core.validators
import utils.models
import utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.FileField(blank=True, null=True, storage=utils.storage.select_public_storage, upload_to='profiles_public/%Y/%W/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png')), utils.models.MaxFileSizeValidator(2097152)], verbose_name='picture'),
        ),
    ]
