# Generated by Django 6.0.6 on 2026-07-22 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the creation of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update of the object', verbose_name='updated at')),
                ('email', models.EmailField(blank=True, editable=False, max_length=254, verbose_name='email')),
                ('success', models.BooleanField(default=False, editable=False, verbose_name='success')),
                ('remote_ua', models.CharField(blank=True, editable=False, max_length=150, verbose_name='remote user agent')),
                ('remote_addr', models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='remote address')),
                ('user', models.ForeignKey(blank=True, editable=False, help_text='successful login user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logins', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'login attempt',
                'verbose_name_plural': 'login attempts',
                'ordering': ('-created_at',),
            },
        ),
    ]
