name: Backend Check

on:
  push:
    branches:
      - 'main'
    paths:
      - 'backend/**.py'
      - 'backend/uv.lock'
      - 'backend/pyproject.toml'
      - 'Dockerfile*'
      - 'docker-compose*.yml'
      - '.github/workflows/backend_check.yml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'backend/**.py'
      - 'backend/requirements*.*'
      - 'backend/pyproject.toml'
      - 'Dockerfile*'
      - 'docker-compose*.yml'
      - '.github/workflows/backend_check.yml'

jobs:
  static_analysis:
    name: Run static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          working-directory: ./backend
          python-version: "3.13"
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock

      - name: Install Ruff with uv
        working-directory: ./backend
        run: |
          uv sync --only-group ruff

      - name: Check formatting with Ruff
        working-directory: ./backend
        run: |
          uv run ruff format --check .

      - name: Check linting using Ruff
        working-directory: ./backend
        run: |
          uv run ruff check --select I .


  checking_migrations:
    name: Check for migrations
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          working-directory: ./backend
          python-version: "3.13"
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock

      - name: Install dependencies
        working-directory: ./backend
        run: |
          uv sync

      - name: Check for migrations
        working-directory: ./backend
        env:
          SECRET_KEY: testing
        run: |
          set -a
          uv run ./manage.py makemigrations --check --dry-run
          set +a


  tests:
    name: Run backend tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          working-directory: ./backend
          python-version: "3.13"
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock

      - name: Install dependencies
        working-directory: ./backend
        env:
          SECRET_KEY: testing
        run: |
          uv sync
          sudo apt-get update
          sudo apt-get install gettext
          uv run ./manage.py compilemessages

      - name: Run tests
        working-directory: ./backend
        env:
          SECRET_KEY: testing
          DJANGO_SETTINGS_MODULE: funding.test_settings
        run: |
          uv run pytest -Wd --cov --cov-report=xml --cov-report=term-missing --cov-fail-under=60 -n auto
