on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

name: Build Docker image

jobs:
  build:
    uses: commitglobal/.github/.github/workflows/build-push-image.yml@main
    with:
      images: commitglobal/funding-call
      dockerfile: ./docker/dockerfiles/Dockerfile
    secrets:
      username: ${{ secrets.DOCKER_HUB_USERNAME }}
      token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
